project:
  type: website

website:
  title: "Bringing Data to Life"
  description: "L"
  image: /media/geospatial.png
  navbar:
    search: true
    logo: /media/geospatial.png
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - icon: github
        href: https://github.com/jordanong09

format:
  html:
    theme: journal
    css: styles.css
    toc: true
    date-format: long
    code-link: true

editor: visual

comments:
  giscus:
    repo: jordanong09/ISSS624_Geospatial

