project:
  type: website

website:
  title: "Bringing Geographical Data to Life"
  description: "L"
  image: /media/geospatial.png
  navbar:
    search: true
    logo: /media/geospatial.png
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: simplex
    css: styles.css
    toc: true
    date-format: long

editor: visual

